

services:
  web:
    deploy:
      resources:
        limits: 
          cpus: '4'
          memory: 6G
        reservations:
          memory: 2G
    build: .
    volumes:
      - ./data:/app/data         
      - ./static:/app/static      
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    environment:
      - AUDIVERIS_PATH=/app/audiveris/build/install/audiveris/bin/audiveris
      - AUDIVERIS_OPTS=-Xmx4g -XX:+UseZGC -Djava.awt.headless=true --add-opens=java.desktop/sun.awt=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
      - OMP_THREAD_LIMIT=4  
      - PYTHONUNBUFFERED=1        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 3